/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScamsRouteImport } from './routes/scams'
import { Route as ScamTrendsRouteImport } from './routes/scam-trends'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OfficialNumbersRouteImport } from './routes/official-numbers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as CheckRouteImport } from './routes/check'
import { Route as AppealRouteImport } from './routes/appeal'
import { Route as AdminMfaRouteImport } from './routes/admin-mfa'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmbedCheckRouteImport } from './routes/embed_.check'

const ScamsRoute = ScamsRouteImport.update({
  id: '/scams',
  path: '/scams',
  getParentRoute: () => rootRouteImport,
} as any)
const ScamTrendsRoute = ScamTrendsRouteImport.update({
  id: '/scam-trends',
  path: '/scam-trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficialNumbersRoute = OfficialNumbersRouteImport.update({
  id: '/official-numbers',
  path: '/official-numbers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckRoute = CheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealRoute = AppealRouteImport.update({
  id: '/appeal',
  path: '/appeal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMfaRoute = AdminMfaRouteImport.update({
  id: '/admin-mfa',
  path: '/admin-mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedCheckRoute = EmbedCheckRouteImport.update({
  id: '/embed_/check',
  path: '/embed/check',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-mfa': typeof AdminMfaRoute
  '/appeal': typeof AppealRoute
  '/check': typeof CheckRoute
  '/embed': typeof EmbedRoute
  '/emergency': typeof EmergencyRoute
  '/login': typeof LoginRoute
  '/official-numbers': typeof OfficialNumbersRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/scam-trends': typeof ScamTrendsRoute
  '/scams': typeof ScamsRoute
  '/embed/check': typeof EmbedCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-mfa': typeof AdminMfaRoute
  '/appeal': typeof AppealRoute
  '/check': typeof CheckRoute
  '/embed': typeof EmbedRoute
  '/emergency': typeof EmergencyRoute
  '/login': typeof LoginRoute
  '/official-numbers': typeof OfficialNumbersRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/scam-trends': typeof ScamTrendsRoute
  '/scams': typeof ScamsRoute
  '/embed/check': typeof EmbedCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-mfa': typeof AdminMfaRoute
  '/appeal': typeof AppealRoute
  '/check': typeof CheckRoute
  '/embed': typeof EmbedRoute
  '/emergency': typeof EmergencyRoute
  '/login': typeof LoginRoute
  '/official-numbers': typeof OfficialNumbersRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/scam-trends': typeof ScamTrendsRoute
  '/scams': typeof ScamsRoute
  '/embed_/check': typeof EmbedCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-mfa'
    | '/appeal'
    | '/check'
    | '/embed'
    | '/emergency'
    | '/login'
    | '/official-numbers'
    | '/privacy'
    | '/report'
    | '/scam-trends'
    | '/scams'
    | '/embed/check'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-mfa'
    | '/appeal'
    | '/check'
    | '/embed'
    | '/emergency'
    | '/login'
    | '/official-numbers'
    | '/privacy'
    | '/report'
    | '/scam-trends'
    | '/scams'
    | '/embed/check'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-mfa'
    | '/appeal'
    | '/check'
    | '/embed'
    | '/emergency'
    | '/login'
    | '/official-numbers'
    | '/privacy'
    | '/report'
    | '/scam-trends'
    | '/scams'
    | '/embed_/check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminMfaRoute: typeof AdminMfaRoute
  AppealRoute: typeof AppealRoute
  CheckRoute: typeof CheckRoute
  EmbedRoute: typeof EmbedRoute
  EmergencyRoute: typeof EmergencyRoute
  LoginRoute: typeof LoginRoute
  OfficialNumbersRoute: typeof OfficialNumbersRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportRoute: typeof ReportRoute
  ScamTrendsRoute: typeof ScamTrendsRoute
  ScamsRoute: typeof ScamsRoute
  EmbedCheckRoute: typeof EmbedCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scams': {
      id: '/scams'
      path: '/scams'
      fullPath: '/scams'
      preLoaderRoute: typeof ScamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scam-trends': {
      id: '/scam-trends'
      path: '/scam-trends'
      fullPath: '/scam-trends'
      preLoaderRoute: typeof ScamTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/official-numbers': {
      id: '/official-numbers'
      path: '/official-numbers'
      fullPath: '/official-numbers'
      preLoaderRoute: typeof OfficialNumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check': {
      id: '/check'
      path: '/check'
      fullPath: '/check'
      preLoaderRoute: typeof CheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal': {
      id: '/appeal'
      path: '/appeal'
      fullPath: '/appeal'
      preLoaderRoute: typeof AppealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-mfa': {
      id: '/admin-mfa'
      path: '/admin-mfa'
      fullPath: '/admin-mfa'
      preLoaderRoute: typeof AdminMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed_/check': {
      id: '/embed_/check'
      path: '/embed/check'
      fullPath: '/embed/check'
      preLoaderRoute: typeof EmbedCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminMfaRoute: AdminMfaRoute,
  AppealRoute: AppealRoute,
  CheckRoute: CheckRoute,
  EmbedRoute: EmbedRoute,
  EmergencyRoute: EmergencyRoute,
  LoginRoute: LoginRoute,
  OfficialNumbersRoute: OfficialNumbersRoute,
  PrivacyRoute: PrivacyRoute,
  ReportRoute: ReportRoute,
  ScamTrendsRoute: ScamTrendsRoute,
  ScamsRoute: ScamsRoute,
  EmbedCheckRoute: EmbedCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
