-- Family Shield consent and notification idempotency.
--
-- Safety model:
-- - Manual one-tap alerts remain available after an invite is accepted.
-- - Automatic high-risk alerts are OFF by default and require independent
--   consent from both the guardian and the trusted contact.
-- - A notification claim is committed before Telegram delivery so concurrent
--   workers and update retries cannot send the same alert twice.
-- - Claims contain operational metadata only. Checked text, URLs, phone
--   numbers, usernames, codes, screenshots, OCR and report details are never
--   stored here.

ALTER TABLE public.telegram_family_shield
  ADD COLUMN guardian_auto_alerts_enabled BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN trusted_auto_alerts_enabled BOOLEAN NOT NULL DEFAULT false;

COMMENT ON COLUMN public.telegram_family_shield.guardian_auto_alerts_enabled IS
  'Guardian consent for automatic high-risk alerts. False by default; both parties must opt in.';
COMMENT ON COLUMN public.telegram_family_shield.trusted_auto_alerts_enabled IS
  'Trusted-contact consent for automatic high-risk alerts. False by default; both parties must opt in.';

CREATE SCHEMA IF NOT EXISTS private;

CREATE TABLE private.telegram_family_notification_claims (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  family_id UUID NOT NULL
    REFERENCES public.telegram_family_shield(id)
    ON DELETE CASCADE,
  idempotency_key TEXT NOT NULL
    CHECK (length(idempotency_key) BETWEEN 16 AND 160),
  mode TEXT NOT NULL CHECK (mode IN ('manual', 'automatic')),
  status TEXT NOT NULL DEFAULT 'claimed'
    CHECK (status IN ('claimed', 'delivered', 'failed')),
  claimed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '7 days'),
  UNIQUE (family_id, idempotency_key),
  CHECK (
    (status = 'claimed' AND completed_at IS NULL)
    OR (status IN ('delivered', 'failed') AND completed_at IS NOT NULL)
  )
);

CREATE INDEX idx_telegram_family_notification_claims_expiry
  ON private.telegram_family_notification_claims(expires_at);

ALTER TABLE private.telegram_family_notification_claims ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON private.telegram_family_notification_claims
  FROM PUBLIC, anon, authenticated;

COMMENT ON TABLE private.telegram_family_notification_claims IS
  'Short-lived metadata-only claims preventing duplicate Family Shield Telegram alerts; no checked artifact or secret.';
COMMENT ON COLUMN private.telegram_family_notification_claims.idempotency_key IS
  'Opaque SHA-256 marker generated by server code; never raw Telegram content or a user-supplied artifact.';

CREATE OR REPLACE FUNCTION public.claim_telegram_family_notification(
  p_guardian_telegram_user_id BIGINT,
  p_mode TEXT,
  p_idempotency_key TEXT,
  p_cooldown_seconds INTEGER DEFAULT 120
)
RETURNS TABLE(
  decision TEXT,
  claim_id UUID,
  family_id UUID,
  trusted_chat_id BIGINT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_now TIMESTAMPTZ := pg_catalog.clock_timestamp();
  v_family public.telegram_family_shield%ROWTYPE;
  v_existing_claim UUID;
  v_claim_id UUID;
BEGIN
  IF p_guardian_telegram_user_id IS NULL
     OR p_guardian_telegram_user_id <= 0
     OR p_mode IS NULL
     OR p_mode NOT IN ('manual', 'automatic')
     OR p_idempotency_key IS NULL
     OR length(p_idempotency_key) < 16
     OR length(p_idempotency_key) > 160
     OR p_cooldown_seconds IS NULL
     OR p_cooldown_seconds < 1
     OR p_cooldown_seconds > 86400 THEN
    RETURN QUERY
    SELECT
      'unavailable'::TEXT,
      NULL::UUID,
      NULL::UUID,
      NULL::BIGINT;
    RETURN;
  END IF;

  DELETE FROM private.telegram_family_notification_claims
  WHERE expires_at <= v_now;

  SELECT *
  INTO v_family
  FROM public.telegram_family_shield
  WHERE guardian_telegram_user_id = p_guardian_telegram_user_id
    AND status = 'active'
  FOR UPDATE;

  IF NOT FOUND OR v_family.trusted_chat_id IS NULL THEN
    RETURN QUERY
    SELECT
      'not_linked'::TEXT,
      NULL::UUID,
      NULL::UUID,
      NULL::BIGINT;
    RETURN;
  END IF;

  IF p_mode = 'automatic'
     AND NOT (
       v_family.guardian_auto_alerts_enabled
       AND v_family.trusted_auto_alerts_enabled
     ) THEN
    RETURN QUERY
    SELECT
      'auto_alerts_disabled'::TEXT,
      NULL::UUID,
      v_family.id,
      NULL::BIGINT;
    RETURN;
  END IF;

  SELECT id
  INTO v_existing_claim
  FROM private.telegram_family_notification_claims AS claims
  WHERE claims.family_id = v_family.id
    AND claims.idempotency_key = p_idempotency_key;

  IF FOUND THEN
    RETURN QUERY
    SELECT
      'duplicate'::TEXT,
      v_existing_claim,
      v_family.id,
      NULL::BIGINT;
    RETURN;
  END IF;

  IF v_family.last_notified_at IS NOT NULL
     AND v_family.last_notified_at
       > v_now - pg_catalog.make_interval(secs => p_cooldown_seconds) THEN
    RETURN QUERY
    SELECT
      'cooldown'::TEXT,
      NULL::UUID,
      v_family.id,
      NULL::BIGINT;
    RETURN;
  END IF;

  INSERT INTO private.telegram_family_notification_claims(
    family_id,
    idempotency_key,
    mode,
    status,
    claimed_at,
    expires_at
  )
  VALUES (
    v_family.id,
    p_idempotency_key,
    p_mode,
    'claimed',
    v_now,
    v_now + interval '7 days'
  )
  RETURNING id INTO v_claim_id;

  -- Reserve the cooldown window in the same transaction as the claim. This is
  -- intentionally done before the network call: duplicate prevention is safer
  -- than retrying an alert whose Telegram delivery result may be ambiguous.
  UPDATE public.telegram_family_shield
  SET last_notified_at = v_now,
      updated_at = v_now
  WHERE id = v_family.id
    AND status = 'active';

  RETURN QUERY
  SELECT
    'claimed'::TEXT,
    v_claim_id,
    v_family.id,
    v_family.trusted_chat_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.complete_telegram_family_notification(
  p_claim_id UUID,
  p_delivered BOOLEAN
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_updated INTEGER := 0;
BEGIN
  IF p_claim_id IS NULL OR p_delivered IS NULL THEN
    RETURN false;
  END IF;

  UPDATE private.telegram_family_notification_claims
  SET status = CASE WHEN p_delivered THEN 'delivered' ELSE 'failed' END,
      completed_at = pg_catalog.clock_timestamp()
  WHERE id = p_claim_id
    AND status = 'claimed';

  GET DIAGNOSTICS v_updated = ROW_COUNT;
  RETURN v_updated = 1;
END;
$$;

REVOKE ALL ON FUNCTION public.claim_telegram_family_notification(BIGINT, TEXT, TEXT, INTEGER)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.complete_telegram_family_notification(UUID, BOOLEAN)
  FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.claim_telegram_family_notification(BIGINT, TEXT, TEXT, INTEGER)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.complete_telegram_family_notification(UUID, BOOLEAN)
  TO service_role;

COMMENT ON FUNCTION public.claim_telegram_family_notification(BIGINT, TEXT, TEXT, INTEGER) IS
  'Atomically claims a metadata-only Family Shield alert after consent, cooldown and idempotency checks; service-role only.';
COMMENT ON FUNCTION public.complete_telegram_family_notification(UUID, BOOLEAN) IS
  'Records the delivery outcome for a Family Shield notification claim; service-role only.';
